theme: jekyll-theme-merlot
title: Welcome to the Automatic Data Retrieval Using R tutorial for Gorilla!
description: This is just a basic tutorial on how to get started with the HTTR package to pull data from Gorilla.
